# Codecov configuration for vnbdigitaler
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
